errbit:
  image: errbit/errbit:latest
  ports:
    - "5000:5000"
  links:
    - mongo
  environment:
    - PORT=5000
    - RACK_ENV=production
    - MONGO_URL=mongodb://mongo:27017/errbit
mongo:
  image: mongo:3.2
  ports:
    - "27017"
